Заготовки приложений + некоторые доработки
Parus-Sail/Deve-Joint pull request #14
Opened 2023-06-29 08:14 UTC by DashViolin

Созданы приложения проектов и вакансий, поправлен файл настроек, настроен главный роутер. Название главного приложения приведено в соотвествие с остальными, исправлены шаблоны.

2023-06-29 12:02 UTC, Sergiusz2try requested changes

2023-06-29 18:21 UTC, segonaz commented on app/DeveJoint/settings.py
> +    # "authapp" # разве простого указания authapp не достаточно?
А зачем такая конструкция в url
from .apps import MainpageappConfig
app_name = MainpageappConfig.name
Можно же просто сразу написать сразу имя.

2023-06-29 18:21 UTC, segonaz commented on app/DeveJoint/settings.py
> -        "PORT": os.getenv("PG_PORT") or "16432",
Я думаю что кто-то пользуется этим. Не нужно убирать.

2023-06-30 07:23 UTC, DashViolin commented on app/DeveJoint/settings.py
> +    "mainapp",
проверила, не вылезают

2023-06-30 07:24 UTC, DashViolin commented on app/DeveJoint/settings.py
> -        "PORT": os.getenv("PG_PORT") or "16432",
ок, поправлю

2023-06-30 07:29 UTC, DashViolin commented on app/DeveJoint/settings.py
> +    # "authapp" # разве простого указания authapp не достаточно?
В apps.py генерится так, без app_name локальный роутер не работает. Взято из курса по django)

2023-06-30 07:35 UTC, V-U-Simon commented on app/DeveJoint/settings.py
> +    "mainapp",
Тогда уж python way — main_app. (вопрос вкусовщины)

А так полностью согласен, будь моя воля, переименовал бы и DeveJoint в Core или Config (т.к. именно там все основные настройки проекта)))

2023-06-30 07:37 UTC, DashViolin commented on app/DeveJoint/settings.py
> +    "mainapp",
Полностью согласна) Так что делаем?

2023-06-30 11:46 UTC, V-U-Simon commented on app/mainapp/templates/mainapp/index.html
Возможно стоит перенести все связанное с job в апп с вакансиями

2023-06-30 12:16 UTC, DashViolin commented on app/mainapp/templates/mainapp/index.html
может это сделать в следующем PR? Иначе держим остальных

2023-06-30 19:14 UTC, segonaz commented on app/DeveJoint/settings.py
> +    "mainapp",
Я за main_app и config

2023-06-30 22:07 UTC, segonaz commented on app/DeveJoint/settings.py
> +    # "authapp" # разве простого указания authapp не достаточно?
Это был ответ к этому вопросу:
"authapp.apps.AuthappConfig",
 # "authapp" # разве простого указания authapp не достаточно?

app_name  требуется для локального роутера и мы берем его из конфига.
app_name = MainpageappConfig.name
в settings мы не указываем имя напрямую и берем app из конфига.
authapp.apps.AuthappConfig
Если менять что-то надо будет так в одном месте.
Если не нравиться пиши имя в settings напрямую, окей. Это просто ответ.

2023-06-30 22:11 UTC, segonaz approved these changes
Комментарий оставил, делай как считаешь нужным. Главное чтобы было одинаково.

2023-07-01 10:19 UTC, DashViolin commented on app/DeveJoint/settings.py
> +    "mainapp",
Готово, все тут: cd3c4d995e7ea8e39d782fa5570b0d24deb3597d

2023-07-01 10:41 UTC, DashViolin commented on app/mainapp/templates/mainapp/index.html
Сделано тут: 8124c845518dfa40818e53e855e71564deb7cc4e

2023-07-01 15:23 UTC, Sergiusz2try approved these changes
Все хорошо

2023-07-01 15:27 UTC, merged