Feature/os 95
Parus-Sail/Deve-Joint pull request #9
Opened 2023-06-26 23:01 UTC by segonaz

Добавлено приложение для авторизации, регистрации. Файлы главного приложения, шаблоны из ветки OS-18-main-page.

2023-06-27 12:33 UTC, kataklizm88 approved these changes

2023-06-28 08:43 UTC, V-U-Simon requested changes
Оставил комментарий относительно `envfiles/env_dev`

2023-06-28 08:43 UTC, V-U-Simon commented on envfiles/env_dev
> +PG_EXT_PORT=16432
В `docket-compose.yaml` указано: 
```
    ports:
      - "${PG_EXT_PORT}:5432"
```

Таким образом (`HOST_PORT:CONTAINER_PORT`):
- в докер сети контейнеры могут общаться через порт 5432 
(переменная PG_EXT_PORT не меняет стандартный порт на новый, в отличие от PGPORT https://postgrespro.ru/docs/postgresql/13/app-postgres)

- в случае обращения при локальной разработке достучаться до контейнера можно будте через внешний порт 16432


Таким образом  для корректной работы локально и в сети докер следует указать:
 `PG_EXT_PORT=5432`


В итоге после корректировки конфигов порты должны выглядеть следующим образом:
- локально: `localhost:16432`
- внутри сети докер: `devejoint-db:5432`

2023-06-28 10:36 UTC, V-U-Simon approved these changes

2023-06-28 11:26 UTC, V-U-Simon commented on app/DeveJoint/settings.py
> +        "PORT": os.getenv("PG_PORT") or "16432",
локально: `localhost:16432`
внутри сети докер: `devejoint-db:5432`

2023-06-28 13:25 UTC, Sergiusz2try approved these changes

2023-06-28 14:25 UTC, segonaz commented on app/DeveJoint/settings.py
> +        "PORT": os.getenv("PG_PORT") or "16432",
Pycharm использует для локального запуска .env файл. В этом файле имя переменной отличается от переменной в файле с конфигурацией с докером, там это выглядит так.
ports:
      - "${PG_EXT_PORT}:5432"
Докер не открывает наружу порт, потому-что такой переменной нет в .env файле. Порта 16432 нет наружи, pycharm не может к нему подсоединиться, даже если он считает ее локально.
Я взял переменную из докер файла (PG_EXT_PORT) и ее поместил в settings и в .env файлы. Это же логично что, переменная должны быть везде одна? Проблем с запуском не было.

2023-06-28 15:06 UTC, merged